### ISSUE TITLE
NullPointerException for a non-exceptional case of zero addresses

### ISSUE THREAD

**Issue by Heinerion** [Heinerion/InvoiceManager#33]
A NullPointerException is thrown if no address is available (see also #26).

That is no exceptional case, it is the default case when starting the application for the first time.
Stacktrace is:
```haskell
Exception in thread "Thread-0" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:222)
	at de.heinerion.betriebe.data.MemoryBank.getSortedEntries(MemoryBank.java:121)
	at de.heinerion.betriebe.data.MemoryBank.getAddresses(MemoryBank.java:41)
	at de.heinerion.betriebe.data.DataBase.getAddresses(DataBase.java:60)
	at de.heinerion.invoice.view.swing.home.receiver.AddressChooserPanel.refreshBoxes(AddressChooserPanel.java:139)
	at de.heinerion.invoice.view.swing.home.receiver.AddressPanel.refresh(AddressPanel.java:21)
	at de.heinerion.invoice.view.swing.home.ReceiverPanel.refresh(ReceiverPanel.java:54)
	at de.heinerion.invoice.view.swing.home.ApplicationFrameImpl.refreshBoxes(ApplicationFrameImpl.java:127)
	at de.heinerion.invoice.view.swing.home.ApplicationFrameImpl.refresh(ApplicationFrameImpl.java:119)
	at de.heinerion.invoice.view.GuiStarter.collectData(GuiStarter.java:41)
	at de.heinerion.invoice.view.GuiStarter.lambda$startDataThread$0(GuiStarter.java:33)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Heinerion** [comment]
duplicate of the mentioned #26
